spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MyHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000      # 10 dk
      max-lifetime: 1800000     # 30 dk
      connection-timeout: 20000 # 20s
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8050
